My_Second_Project/My_Second_Project/Login_App/urls.py
from django.conf.urls import include
from django.urls import path
from Login_App import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

app_name = 'Login_App'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name='login'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Second_Project/My_Second_Project/My_Second_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login_App.urls')),
]

My_Second_Project/My_Second_Project/Login_App/models.py
from django.db import models
from django.contrib.auth.models import User #authorized models theke userk import kora

#username, password, email
# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    facebook_id = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __self__(self):
        return self.user.username

My_Second_Project/My_Second_Project/Login_App/forms.py
from django import forms
from django.contrib.auth.models import User
from Login_App.models import UserInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password')



class UserInfoForm(forms.ModelForm):
    class Meta():
        model = UserInfo
        fields = ('facebook_id', 'profile_pic')

My_Second_Project/My_Second_Project/Login_App/views.py
from django.shortcuts import render
from Login_App.forms import UserForm, UserInfoForm
from Login_App.models import UserInfo
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse


# Create your views here.
def login_page(request):
    dict = {'title': "Login Page"}
    return render(request, 'Login_App/login.html', context=dict)

def user_login(request):
    dict = {'title': "Login Page"}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate( username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('Login_App:index'))
            else:
                return HttpResponse('Your account is not active') 
            
        else:
            return HttpResponse('Username or password is incorrect')
        
    else:
        return HttpResponseRedirect(reverse('Login_App:login'))
    
@login_required
def user_logout(request):  
    logout(request)
    return HttpResponseRedirect(reverse('Login_App:index'))


def index(request):
    dict = {'title': "Home Page"}
    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id
        user_basic_info = User.objects.get(pk=user_id)
        user_more_info = UserInfo.objects.get(user__pk=user_id)
        dict.update({'user_basic_info': user_basic_info, 'user_more_info': user_more_info})
    
    return render(request, 'Login_App/index.html', context=dict)

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_info_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_info = user_info_form.save(commit=False)
            user_info.user = user

            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']

            user_info.save()

            registered = True
        
    else:
        user_form = UserForm()
        user_info_form = UserInfoForm()

        

    dict = {'title': "Registration Page",'user_form': user_form, 'user_info_form': user_info_form, 'registered':registered}
    return render(request, 'Login_App/register.html', context=dict)

My_Second_Project/My_Second_Project/templates/Login_App/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'Login_App:index' %}">Home</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Login_App:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Login_App:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Login_App:login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
    </nav>
    <div class="container" style="padding-top:20px">

        {% block body_block %}
        
        {% endblock %}

    </div>
    
</body>
</html>

My_Second_Project/My_Second_Project/templates/Login_App/index.html
{% extends "login_App/base.html" %}
{% block body_block %}
<h2>Index Page</h2>
{% if user.is_authenticated %}
<p>Hi {{ user_basic_info.username }},</p>
<p>{{ user_basic_info.email }}</p>
<img src="/media/{{ user_basic_info.profile_pic }}" width="100px">
<p><a href="{{ user_more_info.facebook_id }}">Facebook Profile</a> </p>
{% else %}
<div class="alert alert-primary">You are not logged in. Please login!!"</div>
{% endif %}
{% endblock  %}

My_Second_Project/My_Second_Project/templates/Login_App/login.html
<!DOCTYPE html>
{% extends "Login_App/base.html" %}

{% block body_block %}

<h3>Please Login!</h3>
<div class="container">
<form action="{% url 'Login_App:user_login'%}" method="POST">
    <label for="username">Username</label>
    <input type="text" name="username" placeholder="Enter Username.." required class="form-control">
    <label for="password">Password</label>
    <input type="password" name="password" placeholder="Enter Password.." required class="form-control">
    <br>
    {% csrf_token %}
    <input type="submit" name="submit" value="Login">
</form>
</div>
{% endblock %}

My_Second_Project/My_Second_Project/templates/Login_App/register.html
<!DOCTYPE html>
{% extends "Login_App/base.html" %}
{% load static %}
{% block body_block %}
{% if registered %}
<div class="alert alert-success">Congratulations! Registration Successful!!</div>
{% else %}
<div class="container">
    <form enctype="multipart/form-data" method="POST"><!--"enctype"= encrypt kore, kono file upload korte hole dite hobe -->
        {{ user_form.as_p }}
        {{ user_info_form.as_p }}
        {% csrf_token %}
        <input type="submit" name="submit" value="Register">
    </form>
</div> 
{% endif %}
{% endblock %}